<?php

/** Get checkout data to be available for precessing in frontend. */
$lunarCheckoutConfig = $block->getCheckoutData()->getSerializedCheckoutConfigs();
$lunarPaymentMethod = $block->getSelectedMethodCode();

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/**
 * Insert component script code to page if payment method match
 */
if ('lunarpaymentmethod' === $lunarPaymentMethod) {

    /** Set checkout data as window variables. */
    $scriptString = "window.checkoutConfig = '{$block->escapeJs($lunarCheckoutConfig)}';";
    $scriptString .= "window.paymentMethod = '{$block->escapeJs($lunarPaymentMethod)}';";
    /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);

    /** Insert multishipping component */
    echo /* @noEscape */ $secureRenderer->renderTag('script', [
        'src' => $block->getViewFileUrl('Lunar_Payment::js/view/payment/lunarpaymentmethod/multishipping.js'),
    ], null, false);
}

/** HOSTED CHECKOUT */
if ('lunarpaymenthosted' === $lunarPaymentMethod || 'lunarmobilepayhosted' === $lunarPaymentMethod) {
    echo /* @noEscape */ $secureRenderer->renderTag('script', [
        'src' => $block->getViewFileUrl('Lunar_Payment::js/view/payment/hostedcheckout/multishipping.js'),
    ], null, false);
}

?>
