<?php

/** Get checkout data to be available for precessing in frontend. */
$lunarCheckoutConfig = $block->getCheckoutData()->getSerializedCheckoutConfigs();
$lunarPaymentMethod = $block->getSelectedMethodCode();

/**
 * Insert component script code to page if payment method match
 */
if ('lunarpaymentmethod' === $lunarPaymentMethod) {

    /** Set checkout data as window variables. */
    echo '<script>window.checkoutConfig = ' . $lunarCheckoutConfig . '</script>';
    echo '<script>window.paymentMethod = "' . $lunarPaymentMethod . '"</script>';

    /** Insert multishipping component */
    echo '<script src="' . $block->getViewFileUrl('Lunar_Payment::js/view/payment/lunarpaymentmethod/multishipping.js') . '"></script>';
}

/** HOSTED CHECKOUT */
if ('lunarpaymenthosted' === $lunarPaymentMethod || 'lunarmobilepayhosted' === $lunarPaymentMethod) {
    echo '<script src="' . $block->getViewFileUrl('Lunar_Payment::js/view/payment/hostedcheckout/multishipping.js') . '"></script>';
}

?>
