<?php
/** Get checkout data to be available for precessing in frontend. */
$checkoutConfig = $block->getCheckoutData()->getSerializedCheckoutConfigs();
$paymentMethod = $block->getSelectedMethodCode();

/** Save checkout data in frontend variables. */
echo '<script type="text/javascript">window.checkoutConfig = ' . $checkoutConfig . '</script>';
echo '<script type="text/javascript">window.paymentMethod = "' . $paymentMethod . '"</script>';

/**
 * Insert component script code to page if payment method match
 */
if ('lunarpaymentmethod' === $paymentMethod) {
    echo '<script src="' . $block->getViewFileUrl('Lunar_Payment::js/plugin-multishipping.js') . '"></script>';
}
?>
