<style>
  #lunarpaymentmethod_logs_buttons_container {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }

  #lunarpaymentmethod_logs_logs_message {
    margin-top: 8px;
  }
</style>


<div id="lunarpaymentmethod_logs_buttons_container">
  <button id="lunarpaymentmethod_logs_export_button" disabled>Export logs</button>
  <button id="lunarpaymentmethod_logs_delete_button" disabled>Delete logs</button>
</div>
<p id="lunarpaymentmethod_logs_logs_message">this is a message</p>


<script type="text/javascript">
  /**
   * Show/hide specific fields based on query parameter
   */
  if (
    "?debug" !== document.location.search
    && 'test' !== jQuery(`#row_payment_us_lunarpaymentmethod_transaction_mode option:selected`).val()
  ) {
      jQuery(`#row_payment_us_lunarpaymentmethod_transaction_mode`).hide();
      jQuery(`#row_payment_us_lunarpaymentmethod_test_app_key`).hide();
      jQuery(`#row_payment_us_lunarpaymentmethod_test_public_key`).hide();
  }

  let lunarExportLogsButton = jQuery(`#lunarpaymentmethod_logs_export_button`);
  let lunarDeleteLogsButton = jQuery(`#lunarpaymentmethod_logs_delete_button`);
  let lunarLogsMessage = jQuery(`#lunarpaymentmethod_logs_logs_message`);
  let lunarLogsEnabledSelector = jQuery(`#payment_us_lunarpaymentmethod_enable_logs`);

  function download(filename, content) {
      var a = document.createElement('a');
      a.setAttribute('href', 'data:application/zip;base64, ' + content);
      a.setAttribute('download', filename);
      a.click();
  }

  jQuery.ajax({
    url: "/lunar/index/Log",
    type: 'POST',
    dataType: 'text',
    data: { "writable": 1 },
    success: function (data) {
      const response = JSON.parse(data);
      if (response.writable) {
        jQuery("lunarpaymentmethod_not_writable").remove();
        lunarLogsEnabledSelector.attr("disabled", false);
      } else {
        lunarLogsEnabledSelector.val("0");
        lunarLogsEnabledSelector.attr("disabled", true);
        lunarLogsEnabledSelector.after('<p id="lunarpaymentmethod_not_writable" class="note" style="color: red; margin-top: 8px;">Cannot enable logs right now<br />Please make sure the following directory is writable:<br /><pre><small>'+response.dir+'</small></pre></p>');
      }
    },
  });

  function checkForLogs() {
    jQuery.ajax({
      url: "/lunar/index/Log",
      type: 'POST',
      dataType: 'text',
      data: { "hasLogs": 1 },
      success: function (data) {
        if (!data) {
          lunarExportLogsButton.attr("disabled", true);
          lunarDeleteLogsButton.attr("disabled", true);
          lunarLogsMessage.html("No logs saved");
        } else {
          lunarExportLogsButton.attr("disabled", false);
          lunarDeleteLogsButton.attr("disabled", false);
          lunarLogsMessage.html("");
        }
      }
    });
  }

  checkForLogs();

  lunarDeleteLogsButton.on("click", (event) => {
    event.preventDefault();

    if (!confirm("Are you sure you want to delete the logs?")) {
      return;
    }

    lunarDeleteLogsButton.attr("disabled", true);
    lunarDeleteLogsButton.html("Loading...");

    jQuery.ajax({
      url: "/lunar/index/Log",
      type: 'POST',
      dataType: 'text',
      data: { "delete": 1 },
      success: function (data) {
        lunarLogsMessage.html("Logs deleted");
        lunarDeleteLogsButton.html("Delete logs");

        setTimeout(checkForLogs, 5000);
      }
    });
  });

  lunarExportLogsButton.on("click", (event) => {
    event.preventDefault();

    lunarExportLogsButton.attr("disabled", true);
    lunarExportLogsButton.html("Loading...");

    jQuery.ajax({
      url: "/lunar/index/Log",
      type: 'POST',
      dataType: 'text',
      data: { "export": 1 },
      success: function (data) {
        download("lunarPaymentLogs.zip", data);

        lunarExportLogsButton.attr("disabled", false);
        lunarExportLogsButton.html("Export logs");
      }
    });
  });
</script>
