<style>
  #lunar_logs_buttons_container {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }

  #lunar_logs_logs_message {
    margin-top: 8px;
  }
</style>
<div id="lunar_logs_buttons_container">
  <button id="lunar_logs_export_button" disabled>Export logs</button>
  <button id="lunar_logs_delete_button" disabled>Delete logs</button>
</div>
<p id="lunar_logs_logs_message">this is a message</p>

<script type="text/javascript">
  const LUNAR = 'lunar';
  const MODULE_CODE = 'lunarpaymentmethod';
  var exportLogsButton = jQuery(`#${LUNAR}_logs_export_button`);
  var deleteLogsButton = jQuery(`#${LUNAR}_logs_delete_button`);
  var logsMessage = jQuery(`#${LUNAR}_logs_logs_message`);
  var pluginLogsEnabledSelector = jQuery(`#payment_us_${MODULE_CODE}_enable_logs`);

  function download(filename, content) {
      var a = document.createElement('a');
      a.setAttribute('href', 'data:application/zip;base64, ' + content);
      a.setAttribute('download', filename);
      a.click();
  }

  jQuery.ajax({
    url: "/lunar/index/Log",
    type: 'POST',
    dataType: 'text',
    data: { "writable": 1 },
    success: function (data) {
      const response = JSON.parse(data);
      if (response.writable) {
        jQuery("#not-writable").remove();
        pluginLogsEnabledSelector.attr("disabled", false);
      } else {
        pluginLogsEnabledSelector.val("0");
        pluginLogsEnabledSelector.attr("disabled", true);
        pluginLogsEnabledSelector.after('<p id="not-writable" class="note" style="color: red; margin-top: 8px;">Cannot enable logs right now<br />Please make sure the following directory is writable:<br /><pre><small>'+response.dir+'</small></pre></p>');
      }
    },
  });

  function checkForLogs() {
    jQuery.ajax({
      url: "/lunar/index/Log",
      type: 'POST',
      dataType: 'text',
      data: { "hasLogs": 1 },
      success: function (data) {
        if (!data) {
          exportLogsButton.attr("disabled", true);
          deleteLogsButton.attr("disabled", true);
          logsMessage.html("No logs saved");
        } else {
          exportLogsButton.attr("disabled", false);
          deleteLogsButton.attr("disabled", false);
          logsMessage.html("");
        }
      }
    });
  }

  checkForLogs();

  deleteLogsButton.on("click", (event) => {
    event.preventDefault();

    if (!confirm("Are you sure you want to delete the logs?")) {
      return;
    }

    deleteLogsButton.attr("disabled", true);
    deleteLogsButton.html("Loading...");

    jQuery.ajax({
      url: "/lunar/index/Log",
      type: 'POST',
      dataType: 'text',
      data: { "delete": 1 },
      success: function (data) {
        logsMessage.html("Logs deleted");
        deleteLogsButton.html("Delete logs");

        setTimeout(checkForLogs, 5000);
      }
    });
  });

  exportLogsButton.on("click", (event) => {
    event.preventDefault();

    exportLogsButton.attr("disabled", true);
    exportLogsButton.html("Loading...");

    jQuery.ajax({
      url: "/lunar/index/Log",
      type: 'POST',
      dataType: 'text',
      data: { "export": 1 },
      success: function (data) {
        download("paymentPluginLogs.zip", data);

        exportLogsButton.attr("disabled", false);
        exportLogsButton.html("Export logs");
      }
    });
  });
</script>
